---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:

    - name: Register font info
      ansible.builtin.command: 'fc-list'
      changed_when: no
      args:
        warn: no
      register: fonts_install_result

    - name: Verify font is instaled
      ansible.builtin.assert:
        that:
          - fonts_install_result.stdout is search('codeface/FreeMono')
